package com.iponlove.app.feature.notifications.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.iponlove.app.core.sync.SyncMeta
import java.time.Instant

/**
 * Room mirror of a `notifications` row. Implements [SyncMeta] for the generic sync engine.
 *
 * Own-user-only: there is no partner variant and this table is never replicated (ADR-0053
 * decision 2). Item 9's "partner logged a debt" notification lands as the *recipient's own*
 * row, generated by their own client from the already-synced debt.
 *
 * [id] is a deterministic composite string (not a uuid) — see
 * [com.iponlove.app.feature.notifications.domain.model.AppNotification].
 *
 * [category] is stored as its raw wire key rather than a Room-converted enum so a category
 * written by a newer client round-trips through this build unchanged instead of being
 * flattened to the local fallback.
 */
@Entity(tableName = "notifications")
data class NotificationEntity(
    @PrimaryKey override val id: String,
    val userId: String,
    val category: String,
    val title: String,
    val body: String,
    val deepLink: String?,
    val isRead: Boolean,
    val createdAt: Instant,
    override val updatedAt: Instant,
    override val isDeleted: Boolean,
    override val serverRev: Long?,
    override val pendingSync: Boolean,
) : SyncMeta
