package com.iponlove.app.core.ui.theme

import androidx.compose.ui.graphics.Color

// Rose
val RoseLight = Color(0xFF9F3758)
val RoseLightOnPrimary = Color(0xFFFFFFFF)
val RoseLightContainer = Color(0xFFFFD9E3)
val RoseLightOnContainer = Color(0xFF3C0016)
val RoseLightBackground = Color(0xFFFFF8F9)
val RoseLightSurface = Color(0xFFFFF8F9)
val RoseLightSurfaceVariant = Color(0xFFEEDCE8)
val RoseDark = Color(0xFFFFB1C3)
val RoseDarkOnPrimary = Color(0xFF65002D)
val RoseDarkContainer = Color(0xFF7B2940)
val RoseDarkOnContainer = Color(0xFFFFD9E3)
val RoseDarkBackground = Color(0xFF161116)
val RoseDarkSurface = Color(0xFF1E1A1E)
val RoseDarkSurfaceVariant = Color(0xFF2A2230)

// Mauve
val MauveLight = Color(0xFF7B4F5E)
val MauveLightOnPrimary = Color(0xFFFFFFFF)
val MauveLightContainer = Color(0xFFFFD8E6)
val MauveLightOnContainer = Color(0xFF31101D)
val MauveLightBackground = Color(0xFFFFF8FA)
val MauveLightSurface = Color(0xFFFFF8FA)
val MauveLightSurfaceVariant = Color(0xFFEEDCE5)
val MauveDark = Color(0xFFEFB8C8)
val MauveDarkOnPrimary = Color(0xFF4C2234)
val MauveDarkContainer = Color(0xFF63384B)
val MauveDarkOnContainer = Color(0xFFFFD8E6)
val MauveDarkBackground = Color(0xFF161115)
val MauveDarkSurface = Color(0xFF1E191D)
val MauveDarkSurfaceVariant = Color(0xFF2A2029)

// Lavender
val LavenderLight = Color(0xFF6750A4)
val LavenderLightOnPrimary = Color(0xFFFFFFFF)
val LavenderLightContainer = Color(0xFFEADDFF)
val LavenderLightOnContainer = Color(0xFF21005D)
val LavenderLightBackground = Color(0xFFFFFBFF)
val LavenderLightSurface = Color(0xFFFFFBFF)
val LavenderLightSurfaceVariant = Color(0xFFE7DEFF)
val LavenderDark = Color(0xFFCFBEFF)
val LavenderDarkOnPrimary = Color(0xFF381E72)
val LavenderDarkContainer = Color(0xFF4F378B)
val LavenderDarkOnContainer = Color(0xFFEADDFF)
val LavenderDarkBackground = Color(0xFF141018)
val LavenderDarkSurface = Color(0xFF1C1820)
val LavenderDarkSurfaceVariant = Color(0xFF27203A)

// Peach
val PeachLight = Color(0xFF9D4F29)
val PeachLightOnPrimary = Color(0xFFFFFFFF)
val PeachLightContainer = Color(0xFFFFDBCF)
val PeachLightOnContainer = Color(0xFF350F00)
val PeachLightBackground = Color(0xFFFFF8F5)
val PeachLightSurface = Color(0xFFFFF8F5)
val PeachLightSurfaceVariant = Color(0xFFEEDDD5)
val PeachDark = Color(0xFFFFB59B)
val PeachDarkOnPrimary = Color(0xFF55200D)
val PeachDarkContainer = Color(0xFF75341A)
val PeachDarkOnContainer = Color(0xFFFFDBCF)
val PeachDarkBackground = Color(0xFF181210)
val PeachDarkSurface = Color(0xFF201816)
val PeachDarkSurfaceVariant = Color(0xFF2C2018)

// Sage
val SageLight = Color(0xFF3F6745)
val SageLightOnPrimary = Color(0xFFFFFFFF)
val SageLightContainer = Color(0xFFC1ECC5)
val SageLightOnContainer = Color(0xFF002109)
val SageLightBackground = Color(0xFFF7FBF5)
val SageLightSurface = Color(0xFFF7FBF5)
val SageLightSurfaceVariant = Color(0xFFDDE8DD)
val SageDark = Color(0xFFA5D0AB)
val SageDarkOnPrimary = Color(0xFF0F3819)
val SageDarkContainer = Color(0xFF265D2F)
val SageDarkOnContainer = Color(0xFFC1ECC5)
val SageDarkBackground = Color(0xFF101411)
val SageDarkSurface = Color(0xFF171C18)
val SageDarkSurfaceVariant = Color(0xFF222824)

// Mocha
val MochaLight = Color(0xFF6D4D3E)
val MochaLightOnPrimary = Color(0xFFFFFFFF)
val MochaLightContainer = Color(0xFFEEDBD2)
val MochaLightOnContainer = Color(0xFF280E07)
val MochaLightBackground = Color(0xFFFFF8F5)
val MochaLightSurface = Color(0xFFFFF8F5)
val MochaLightSurfaceVariant = Color(0xFFEEDDD5)
val MochaDark = Color(0xFFD4BEB4)
val MochaDarkOnPrimary = Color(0xFF3B201A)
val MochaDarkContainer = Color(0xFF533630)
val MochaDarkOnContainer = Color(0xFFEEDBD2)
val MochaDarkBackground = Color(0xFF181210)
val MochaDarkSurface = Color(0xFF1F1815)
val MochaDarkSurfaceVariant = Color(0xFF2B1F1B)
