-- ============================================================================
--  Notification inbox  [v1.7.1 Item 6 / ADR-0053]
--
--  The synced source of truth for every notification the app raises. The OS
--  system-tray push is a best-effort courtesy layered on top ("Way A" —
--  inbox-primary): sync is foreground/reconnect-only (ADR-0012) and the target
--  device force-stops the app above Doze, so a push frequently never fires.
--  Making the inbox authoritative means those notifications wait in the bell
--  instead of being lost.
--
--  Own-user-only: RLS is own-row, there is NO partner redacting view, and the
--  table is never replicated. Item 9's "partner logged a debt" notification
--  lands as the *recipient's own* row, generated by their own client from the
--  already-synced debt — the partner never sees it.
--
--  `id` is TEXT, not uuid: it is a deterministic composite key derived from the
--  event itself (`budget:{budget_id}:{yyyy-MM}:{slot}`, `recurring:{occurrence}`,
--  `debt:{debt_id}`), so the same event detected independently on two clients
--  (phone + web) merges into one row instead of duplicating. Clients generate
--  create-if-absent, never upsert-over, so re-detecting an event can't overwrite
--  read/dismissed state. The row's existence IS the dedup record, which retires
--  the client-side BudgetAlertStore.
--
--  Retention: rows older than 60 days are HARD-deleted by the client sweep — a
--  narrow, sanctioned exception to the tombstone-only rule (ADR-0010),
--  resurrection-safe because every client computes the same cutoff. User
--  dismiss / clear-all, by contrast, are ordinary soft-deletes that sync.
-- ============================================================================

create table notifications (
    id         text primary key,                                    -- deterministic, client-generated
    user_id    uuid not null references users(id) on delete cascade,
    category   text not null,                                       -- 'budget' | 'recurring' | 'couple'
    title      text not null,
    body       text not null,
    deep_link  text,                                                -- NavRegistry module id to open on tap
    is_read    boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    is_deleted boolean not null default false,
    server_rev bigint
);

create trigger trg_rev_notifications
    before insert or update on notifications
    for each row execute function set_server_rev();

create index idx_notifications_rev  on notifications(server_rev);
create index idx_notifications_user on notifications(user_id);

alter table notifications enable row level security;

-- Own rows only, all verbs. `for all` covers the retention sweep's DELETE as well
-- as the ordinary push upsert.
create policy notifications_owner on notifications for all
    using (user_id = auth.uid()) with check (user_id = auth.uid());
